server:
  address: 0.0.0.0
  port: 8080


spring:
  application:
    name: veritas
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
