server:
  address: 0.0.0.0
  port: 8080

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

spring:
  application:
    name: veritas
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

external:
  api:
    url: ${MODEL_MICROSERVICE_URL}
